/*
# Create generated_content table for AI knowledge engine cache

1. Purpose
- Cache structured educational content generated by the AI knowledge engine edge function.
- Each row is keyed by content_node slug + content_type + difficulty, so regeneration is idempotent.
- Single-tenant (no auth): policies allow anon + authenticated CRUD.

2. New Tables
- `generated_content`
  - `id` uuid primary key
  - `node_slug` text NOT NULL — references content_nodes.slug (logical, not FK to avoid cascade issues)
  - `node_id` uuid NOT NULL — references content_nodes(id) ON DELETE CASCADE
  - `content_type` text NOT NULL — 'lesson' | 'quiz' | 'flashcards' | 'summary' | 'glossary'
  - `difficulty` text NOT NULL DEFAULT 'intermediate' — 'beginner' | 'intermediate' | 'advanced'
  - `payload` jsonb NOT NULL — the structured content
  - `created_at` timestamptz DEFAULT now()
  - `updated_at` timestamptz DEFAULT now()
  - UNIQUE (node_slug, content_type, difficulty)

3. Indexes
- idx_generated_content_node on node_id
- idx_generated_content_lookup on (node_slug, content_type, difficulty)

4. Security
- RLS enabled, anon + authenticated CRUD (public reference data).
*/

CREATE TABLE IF NOT EXISTS generated_content (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  node_slug text NOT NULL,
  node_id uuid NOT NULL REFERENCES content_nodes(id) ON DELETE CASCADE,
  content_type text NOT NULL CHECK (content_type IN ('lesson','quiz','flashcards','summary','glossary')),
  difficulty text NOT NULL DEFAULT 'intermediate' CHECK (difficulty IN ('beginner','intermediate','advanced')),
  payload jsonb NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (node_slug, content_type, difficulty)
);

CREATE INDEX IF NOT EXISTS idx_generated_content_node ON generated_content(node_id);
CREATE INDEX IF NOT EXISTS idx_generated_content_lookup ON generated_content(node_slug, content_type, difficulty);

ALTER TABLE generated_content ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_generated_content" ON generated_content;
CREATE POLICY "anon_select_generated_content" ON generated_content FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_generated_content" ON generated_content;
CREATE POLICY "anon_insert_generated_content" ON generated_content FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_generated_content" ON generated_content;
CREATE POLICY "anon_update_generated_content" ON generated_content FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_generated_content" ON generated_content;
CREATE POLICY "anon_delete_generated_content" ON generated_content FOR DELETE
  TO anon, authenticated USING (true);
